manifest:
  remotes:
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk-fingerpunch-vik
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
