manifest:
  remotes:
    - name: rianadon
      url-base: https://github.com/rianadon
  projects:
    - name: zmk-fingerpunch-vik
      remote: rianadon
      revision: main
      import: config/deps.yml
